# Generated by Django 5.2.7 on 2025-10-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Направление')),
                ('code', models.CharField(max_length=10, verbose_name='Код (шифр)')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование профиля')),
                ('full_time', models.BooleanField(default=True, verbose_name='Очная форма обучения')),
                ('part_time', models.BooleanField(default=False, verbose_name='Заочная форма обучения')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.major', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['major', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование дисциплины')),
                ('annotation', models.FileField(upload_to='modules/annotation/', verbose_name='Аннотация')),
                ('syllabus', models.FileField(upload_to='modules/syllabus/', verbose_name='Программа дисциплины (syllabus)')),
                ('assessment_fund', models.FileField(upload_to='modules/assessments/', verbose_name='Фонд оценочных средств')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Дисциплина / Модуль / Практика',
                'verbose_name_plural': 'Дисциплины / Модули / Практики',
            },
        ),
        migrations.CreateModel(
            name='CompetencePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Файл паспорта/программы')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Паспорт / Программа компетенций',
                'verbose_name_plural': 'Паспорта / Программы компетенций',
            },
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='profile_docs/', verbose_name='Документ (файл)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Документ профиля',
                'verbose_name_plural': 'Документы профиля',
            },
        ),
    ]
